FROM node

WORKDIR /app/frontend
COPY package.json /app/frontend

RUN npm config set unsafe-perm true
RUN npm install --unsafe-perm=true

COPY . /app/frontend

RUN npm run build

CMD "mv build /app/api"