version: '3.9'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/code/backend
  django:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    volumes:
      - ./backend:/app/api
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "run", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: