version: "3.3"
   
services:
  postgres:
    image: postgres:12
    env_file:
      - './infrastucture/services/postgres/.env'
  django:
    build: ./backend
    command: "gunicorn backend.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app/api
      - static_volume:/static
      - media_volume:/media
    env_file:
      - './infrastucture/services/postgres/.env'
      - './infrastucture/apps/backend/.env'
    depends_on:
      - postgres
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 8000:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on: 
      - django
  # frontend:
  #   build: ./frontend
  #   command: "npm run start"
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - node-modules:/app/frontend/node_modules
  #   ports:
  #     - "3000:3000"

volumes:
  node-modules:
  static_volume:
  media_volume:
