# Generated by Django 4.0.4 on 2022-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[('WALK', 'Walk'), ('BYCYCLE', 'Bycycle'), ('MOTORBIKE', 'Motorbike'), ('CAR', 'Car')], default='WALK', max_length=128),
        ),
    ]
