# Generated by Django 4.0.4 on 2022-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_courier_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Докемент',
                'verbose_name_plural': 'Докементы',
            },
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Заявка курьера', 'verbose_name_plural': 'Заявки курьеров'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Заявка партнера', 'verbose_name_plural': 'Заявки партнеров'},
        ),
        migrations.AlterField(
            model_name='courier',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки формы'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='type',
            field=models.CharField(choices=[('WALK', 'Walk'), ('BYCYCLE', 'Bycycle'), ('MOTORBIKE', 'Motorbike'), ('CAR', 'Car')], default='WALK', max_length=128, verbose_name='Тип курьера'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки формы'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО ответственного'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='org_email',
            field=models.EmailField(max_length=255, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='org_name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='org_number',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
    ]
