# Generated by Django 4.0.4 on 2022-05-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_documents_alter_courier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документы', 'verbose_name_plural': 'Документы'},
        ),
    ]
